redis:
  enabled: false
  cluster:
    enabled: false
    slaveCount: 0
  password: fake-password
  master:
    persistence:
      enabled: false

nodejs:
  aadIdentityName: xui
  applicationPort: 3000
  memoryLimits: 1024Mi
  cpuLimits: 1000m
  environment:
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CCD_DATA_API_SERVICE: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CCD_DEFINITION_API_SERVICE: http://ccd-definition-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_API_SERVICE: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_WEB_SERVICE: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    RD_PROFESSIONAL_API_SERVICE: http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    S2S_SERVICE: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    ISS_SERVICE: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    FEE_AND_PAY_API: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    REFORM_TEAM: rpx
    REFORM_SERVICE_NAME: xui-ao-webapp
    NODE_ENV: production
    NODE_CONFIG_ENV: production
    UV_THREADPOOL_SIZE: 64
    PUI_ENV: prod
    SESSION_SECRET: secretSauce
    NODE_TLS_REJECT_UNAUTHORIZED: 1
    AO_HTTP_PROXY: http://172.16.0.7:8080
    AO_NO_PROXY: localhost
    PORT: 3000
    NOW: false
    IDAM_CLIENT: xuiaowebapp
    OAUTH_CALLBACK_URL: oauth2/callback
    MAX_LOG_LINE: 80
    EXCEPTION_OPTIONS_MAX_LINES: 1
    INDEX_URL: /
    LOGGING: debug
    PROTOCOL: https
    COOKIE_TOKEN: __auth__
    COOKIE_USER_ID: __userid__
    MICROSERVICE: xui_webapp
    ALLOW_CONFIG_MUTATIONS: 1
    FEATURE_APP_INSIGHTS_ENABLED: true
    FEATURE_SECURE_COOKIE_ENABLED: true
    FEATURE_PROXY_ENABLED: false
    FEATURE_HELMET_ENABLED: true
    FEATURE_REDIS_ENABLED: true
    # Redis
    REDIS_HOST: xui-ao-webapp-{{ .Values.global.environment }}.redis.cache.windows.net
    REDIS_PORT: 6380
    REDIS_SSL_ENABLED: true
    REDIS_KEY_PREFIX: 'activity:'
    REDIS_ACTIVITY_TTL: 5
    REDIS_USER_DETAILS_TTL: 6000
  keyVaults:
    rpx:
      resourceGroup: rpx
      secrets:
        - ao-s2s-client-secret
        - ao-idam-client-secret
        - AppInsightsInstrumentationKey
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
