
nodejs:
  applicationPort: 3000
  memoryLimits: 1024Mi
  cpuLimits: 1000m
  environment:
    REFORM_TEAM: rpx
    REFORM_SERVICE_NAME: xuiao-webapp
    NODE_ENV: production
    UV_THREADPOOL_SIZE: 64
    APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
    S2S_SECRET: ${S2S_SECRET}
    IDAM_SECRET: ${IDAM_SECRET}
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
